### ISSUE TITLE
"Roles" errors on load

### ISSUE THREAD

**Issue by radbasa** [Shahiem/frontend-roles-manager#4]
Clicking on Users > Roles triggers an error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'shahiemseymor_permission_role.user_group_id' in 'where clause'
(SQL: select `shahiemseymor_roles`.*, (select group_concat(shahiemseymor_permissions.name separator ', ') 
from `shahiemseymor_permissions` 
inner join `shahiemseymor_permission_role` on `shahiemseymor_permissions`.`id` = `shahiemseymor_permission_role`.`user_permission_id` 
where `shahiemseymor_permission_role`.`user_group_id` = `shahiemseymor_roles`.`id`) as `permissions`, 
(SELECT COUNT(1) FROM shahiemseymor_assigned_roles 
WHERE role_id = shahiemseymor_roles.id) as `users` 
from `shahiemseymor_roles` order by `name` desc limit 20 offset 0)
....../vendor/laravel/framework/src/Illuminate/Database/Connection.php line 614
```

shahiemseymor_permission_role doesn't indeed have a user_group_id columnn
```
CREATE TABLE `shahiemseymor_permission_role` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `permission_id` int(10) unsigned NOT NULL,
  `role_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

RainLab.User 1.0.15
RainLab.Forum 1.0.12
User Plus 1.0.4
Frontend User Roles manager 1.0.6

**Comment by sulazix** [comment]
Almost the same here : 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'october_local.shahiemseymor_assigned_roles' doesn't exist (SQL: select `new_shahiemseymor_roles`.*, (select group_concat(shahiemseymor_permissions.name separator ', ') from `new_shahiemseymor_permissions` inner join `new_shahiemseymor_permission_role` on `new_shahiemseymor_permissions`.`id` = `new_shahiemseymor_permission_role`.`permission_id` where `new_shahiemseymor_permission_role`.`role_id` = `new_shahiemseymor_roles`.`id`) as `permissions`, (SELECT COUNT(1) FROM shahiemseymor_assigned_roles WHERE role_id = shahiemseymor_roles.id) as `users` from `new_shahiemseymor_roles` order by `name` desc limit 20 offset 0)

**Comment by sulazix** [comment]
Solved for me with a fresh install ...
